services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-container
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-sn-etml}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-root}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
    